baseURL: https://zzgames.online
sourceURL: https://github.com/zzaccount1/zzgames.online
languageCode: en-GB
title: ZZ's blog
publishDir: public
permalinks:
  posts: /posts/:year/:month/:day/:slug

uglyurls: true
pygmentsUseClasses: true

markup:
  enableEmoji: true
  goldmark:
    extensions:
      linkify: true
      typographer: false
    renderer:
      unsafe: true
  highlight:
    style: emacs
  tableOfContents:
    endLevel: 6
    startLevel: 2

outputs:
  taxonomy: ["HTML"]
  taxonomyTerm: ["HTML"]
  page: ["HTML"]
  home: ["HTML"]

outputFormats:
  RSS:
    mediatype: application/rss
    baseName: feed

menu:
  main:
  - identifier: Home
    name: Home
    url: "/"
    weight: 1
  - identifier: Blog
    name: Blog
    url: "/posts/"
    weight: 2
  - identifier: Tags
    name: Tags
    url: "/tags.html"
    weight: 3


params:
  discord: y3vd2vAYru
  discord_user: ZZ#6146
  github: zzaccount1
  projects:
    - name: Autofuncs
      state: ad
      license: MIT
      link: https://github.com/zzaccount1/love-autofuncs
      description:
        A small [Lua](https://lua.org/about.html) module for [Love2D](https://love2d.org) that calls functions like [love.load](https://love2d.org/wiki/love.load), [love.update](https://love2d.org/wiki/love.update), [love.draw](https://love2d.org/wiki/love.draw) etc. that are outside main.lua, without needing to require and call the functions by hand for each script.
      languages:
        - Lua
        - Love2D
    - name: Rail Rush
      state: ad
      license: WTFPL
      link: https://github.com/zzaccount1/rail-rush
      description:
        Small game made for love2d jam 2023.
      languages:
        - Love
        - Lua
    - name: Flappy Love
      state: ab
      license: MIT
      link: https://github.com/zzaccount1/love-flappylove
      description:
        Flappy Bird like game made with love
      languages:
        - Lua
        - Love
    - name: Zalc
      state: ab
      license: MIT
      link: https://github.com/zzaccount1/zalc
      description:
        Basic calculator made with qt in c++
      languages:
        - C++
        - Qt
        - CMake
    - name: RayLib Platformer
      state: ab
      license: MIT
      link: https://github.com/zzaccount1/raylib-platformer
      description:
        Basic platformer made with raylib.
      languages:
        - C++
        - RayLib
    - name: SDL Template
      state: de
      license: MIT
      link: https://github.com/zzaccount1/sdl-template
      description:
        An basic template for sdl projects. Supports only mingw and linux.
      languages:
        - SDL
        - C++
        - CMake
  projectstate:
    ad:
      name: Active
      span: projact
      desc: Projects in active development
    sp:
      name: Side-project
      span: projside
      desc: Side-projects that are in active development, but that aren't in as active development as main projects.
    ma:
      name: Maintained
      span: projmain
      desc: Projects that are being maintained, but that aren't under active development. Primarily applies the projects where ideas have dried up.
    in:
      name: Inactive
      span: projin
      desc: Projects that are currently not receiving any attention.
    po:
      name: Patches only
      span: projpat
      desc: Projects only receiving patches.
    ab:
      name: Abandoned
      span: projaban
      desc: Projects that have been abandoned intentionally
    de:
      name: Dead
      span: projdead
      desc: Projects that have been abandoned due to circumstance, including (but not limited to) loss of interest, loss of need, or my focus being pulled elsewhere.
    upc:
      name: Upcoming
      span: projupc
      desc: Upcoming projects; stay tuned!
